version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    executor: python/default
        
    steps:
      - checkout
      name: Install Dependence
          command: 'apt install libc-ares-dev libev-dev asciidoc xmlto'
      - run:
          chmod 0755 ss-build2.sh && ./ss-build2.sh x86_64 && ./ss-build2.sh arm && ./ss-build2.sh x86
